### ISSUE TITLE
SignalK NodeRed wrong redirection

### ISSUE THREAD

**Issue by mgrouch** [bareboat-necessities/lysmarine_gen#102]
See:

https://github.com/SignalK/node-red-embedded/issues/27

**Comment by Thierry-Myron** [comment]
Same issue as MG
Node-Red V2.1.5
Sinal K: V1.40.0

**Comment by mgrouch** [comment]
In BBN OS there is workaround. 
You run node red in browser,
you can login into SignalK as ‘remember-me’

then close the browser,
Open nodered in browser again and it’s working.

**Comment by Thierry-Myron** [comment]
Thanks
