### ISSUE TITLE
add support for sailor hat

### ISSUE THREAD

**Issue by peronosporos** [bareboat-necessities/lysmarine_gen#143]
sailor hat adds nmea 2000 connectivity with option to be used as power supply at the same time, power supply at 12/24v, battery. firmware is foss. costs 64€.

https://github.com/hatlabs/sh-rpi

https://hatlabs.github.io/sh-rpi

**Comment by mgrouch** [comment]
Sorry I do not have that hardware even to test.  
It’s again up to vendor to support it. 
If vendor supports raspberry pi OS then same methods would work on BBN OS.

**Comment by mgrouch** [comment]
I suggest you opening this as an issue in sailor hat git project.

**Comment by mgrouch** [comment]
@peronosporos 

Anything else is required apart from running install script mentioned here

https://github.com/hatlabs/SH-RPi-daemon

?

Thanks

**Comment by mgrouch** [comment]
Added via add-ons in buster branch. Should make it into next release.
