### ISSUE TITLE
add support for maiana ais

### ISSUE THREAD

**Issue by peronosporos** [bareboat-necessities/lysmarine_gen#144]
it is a foss ais transceiver and gps receiver, diy, convenient, open hardware and cheap. it is sold by openmarine and supported by openplotter.

**Comment by mgrouch** [comment]
I do not have maiana hardware to test. Ideally it would be best if maiana vendor would come up 
with UI (let’s say wxWidgets python)
app to configure it as self contained package. And then I could include it.

**Comment by mgrouch** [comment]
I suggest you opening this as an issue in maiana git project.

**Comment by mgrouch** [comment]
See: https://github.com/peterantypas/maiana/issues/91

**Comment by mgrouch** [comment]
```


cd ~
git clone https://github.com/peterantypas/maiana
python3 ~/maiana/latest/Apps/maiana-update/maiana.py 


```
