### ISSUE TITLE
SSB radio integration

### ISSUE THREAD

**Issue by peronosporos** [bareboat-necessities/lysmarine_gen#145]
better ssb integration and more thorough documentation of it would be of good use. an idea is using ardop and pat winlink client to download grib files, send emails, etc. ideally all set-up in gui.

**Comment by mgrouch** [comment]
I’d love to make it better too. 
However you need to be more specific and might show some scripts/configurations and documentation of use cases. 
There is plenty of software for that 
delivered on the OS image. It needs documentation and HowTos for most common use cases though. I’m looking for help with that from actual users. 

Thanks

**Comment by mgrouch** [comment]
See https://github.com/bareboat-necessities/lysmarine_gen/issues/167
