### ISSUE TITLE
desktop environment

### ISSUE THREAD

**Issue by peronosporos** [bareboat-necessities/lysmarine_gen#146]
consider to use kde or xfce instead of gnome to minimise ram consumption and avoid the gnome bugs. xfce for minimal ram usage possible and good customisability, kde for good ram usage, great customisability and kde connect which could be an interesting addition.

**Comment by mgrouch** [comment]
I evaluated all of the before. 
BBN OS is not really gnome. 
It’s budgie. For same amount of functionality and usability I found it to be best choice. I did all this homework well before.
