### ISSUE TITLE
HF marine info organisation

### ISSUE THREAD

**Issue by peronosporos** [bareboat-necessities/lysmarine_gen#150]
consider making a database for weatherfax and navtex frequencies and timeschedules, and using gps and local time to use a script to automate the process of receiving and decoding the info both with rtl-sdr if it is the only option, and ssb if an installation exists already

**Comment by mgrouch** [comment]
Shouldn’t be difficult to do on condition of having hardware to test it properly. NavTex is few fixed frequencies to scan. Weatherfax is more complicated though and automation with sdr and ssb can be very rig specific

**Comment by mgrouch** [comment]
WeatherFax schedules are installed with opencpn weatherfax plugin

https://www.arachnoid.com/JWX/

https://www.rtl-sdr.com/decoding-morse-code-weather-fax-rtl-sdr/

https://www.rtl-sdr.com/tag/weather-fax/

https://www.rtl-sdr.com/receiving-weather-rtty-rtl-sdr/

**Comment by mgrouch** [comment]
NOAA satellite weather 

Some links:

https://github.com/martinber/noaa-apt

https://github.com/jekhokie/raspberry-noaa-v2

https://www.instructables.com/Raspberry-Pi-NOAA-Weather-Satellite-Receiver/

https://www.rtl-sdr.com/rtl-sdr-tutorial-receiving-noaa-weather-satellite-images/

https://www.rtl-sdr.com/an-alternative-noaa-weather-satellite-tutorial-using-rtl_fm-and-wxtoimg/

https://www.rtl-sdr.com/raspberry-noaa-v2-raspberry-pi-automated-noaa-and-meteor-weather-satellite-capture/

https://www.rtl-sdr.com/creating-an-automated-raspberry-pi-and-rtl-sdr-based-noaa-weather-satellite-station/

https://www.rtl-sdr.com/automatically-receiving-decoding-and-tweeting-noaa-weather-satellite-images-with-a-raspberry-pi-and-rtl-sdr/

https://www.rtl-sdr.com/youtube-tutorial-software-set-up-for-a-portable-raspberry-pi-and-rtl-sdr-based-noaa-weather-satellite-receiver/

**Comment by mgrouch** [comment]
Inmarsat-STD-C decoding with SDR:

https://www.rtl-sdr.com/rtl-sdr-tutorial-decoding-inmarsat-std-c-egc-messages/

https://github.com/cropinghigh/stdcdec

**Comment by mgrouch** [comment]
NavTex decoding with SDR

https://www.arachnoid.com/JNX/

https://www.rtl-sdr.com/decoding-navtex-with-an-sdrplay-rspdx-sdruno-and-yand/

**Comment by mgrouch** [comment]
Requesting and receiving GRIB files via SSB radio

Grib Plugin in OpenCPN

WinLink PAT  https://github.com/la5nta/pat

jpskmail  https://github.com/bareboat-necessities/javapskmail-VK2ETA

**Comment by mgrouch** [comment]
See https://github.com/bareboat-necessities/lysmarine_gen/issues/167
