### ISSUE TITLE
automatic clean-up of older files

### ISSUE THREAD

**Issue by peronosporos** [bareboat-necessities/lysmarine_gen#151]
support automatic removal of old grib, weatherfax, navtex, etc files that are out of date and serve no more any purpose, just add clutter to folders

**Comment by mgrouch** [comment]
Can you script it? 
We would take a script which performs this as a contribution. 
thanks

**Comment by peronosporos** [comment]
i am in the process of learning how to code so my skills are very limited atm

**Comment by mgrouch** [comment]
no plans to add anything for that in near future
can be easily scripted by more experienced user to fit individual needs
