### ISSUE TITLE
Old build detected warning

### ISSUE THREAD

**Issue by Damiasroca** [bareboat-necessities/lysmarine_gen#172]
Constant warning at booting and when opening apps:

`Old buil detected
This app was built a long time ago. Nativifier uses the Chrome 
browser (through Electron), and it's insecure to keep using an old
version of it. Please upgrade Nativifier and rebuild the app`

bbn version: **lysmarine-bbn_2021-11-15-raspios-arm64.img.xz**

**Comment by mgrouch** [comment]
It was fixed in latest version of BBN OS.
Which version are you using?

**Comment by Damiasroca** [comment]
I'm using the latest arm64 version from 2021-11-15

**Comment by mgrouch** [comment]
You need to switch to using 2022-03-30. 
The kernel is also 64-bit on it.
