### ISSUE TITLE
BBN Forums

### ISSUE THREAD

**Issue by jimmid709** [bareboat-necessities/lysmarine_gen#173]
### Discussed in https://github.com/bareboat-necessities/lysmarine_gen/discussions/137

<div type='discussions-op-text'>

<sup>Originally posted by **aviljoenn** December 17, 2021</sup>
Hi All,

Which forum would be the best and most active for BBN Marine Linux OS discussions?
E.g. do the general discussions and questions happen here or Openmarine or elsewhere?
Thank you so much and looking forward to some interaction.
Kind Regards
Andre</div>

**Comment by mgrouch** [comment]
Discussions here https://github.com/bareboat-necessities/lysmarine_gen/discussions

or Raspberry Pi for Boats forum on Facebook
