### ISSUE TITLE
File Explorer not working

### ISSUE THREAD

**Issue by AWeerWolf** [bareboat-necessities/lysmarine_gen#189]
Hello,
I have downloaded the version : 2022-07-13

Button "Files" does nothing.
Menu :  "File Manager" opens "File Manager Preferences" instead of "File Manager"
Menu:  "Thunar File Manager" works fine.

Regards,

**Comment by AWeerWolf** [comment]
After reboot, button "Files" starts "Thunar" => Ok

**Comment by mgrouch** [comment]
It’s already reported here:

https://github.com/bareboat-necessities/lysmarine_gen/issues/49

**Comment by mgrouch** [comment]
Closing as duplicate.
