### ISSUE TITLE
Pican-m not working

### ISSUE THREAD

**Issue by samdowrick** [bareboat-necessities/lysmarine_gen#194]
Followed all the steps in the pican-m manual however it gets stuck at one point. This command - sudo /sbin/ip link set can0 up type can bitrate 250000 - does nothing, just shows a blank screen in terminal. Any reason why this is happening and how can I fix it?

**Comment by mgrouch** [comment]
Where is pican-M manual? Links pls?
What is expected output of your command?

**Comment by samdowrick** [comment]
https://copperhilltech.com/content/pican-m_UGB_20.pdf

**Comment by mgrouch** [comment]
So ip command is not supposed to produce any output. 
output should come from candump command

**Comment by mgrouch** [comment]
I've added more documentation for NMEA 2000

https://bareboat-necessities.github.io/my-bareboat/bareboat-os.html#_nmea_2000

It should make it more clear.

**Comment by samdowrick** [comment]
You're documentation works. In fact I've got so much data flowing in that opencpn keeps freezing. Time to remove some unused software.

**Comment by mgrouch** [comment]
Unused software is not running so it wouldn’t cause OpenCPN freezes. 
You should report OpenCPN freezes via OpenCPN GitHub issues.
