### ISSUE TITLE
Wifi Configuration from headless is difficult

### ISSUE THREAD

**Issue by martincaddick** [bareboat-necessities/lysmarine_gen#207]
I ended up plugging in a cable, setting the fixed resolution, using vnc and then connecting that way. would be so much better if it was scripted ;-)

**Comment by mgrouch** [comment]
Not sure what was difficult. WiFi AP is preconfigured on the image. There is nothing to configure except of changing the password.

**Comment by martincaddick** [comment]
Apologies I should have been more specific. I was trying to have it connect to my existing wifi on the boat and have the address assigned via a dhcp reservation

**Comment by mgrouch** [comment]
To set up wifi without being connected to a network you need monitor and keyboard connected to pi.
So it's not headless at that time. Headless means network and no monitor.

You can script it by putting a script into /boot before first boot.
See: https://bareboat-necessities.github.io/my-bareboat/bareboat-os.html#_customizing_on_first_boot

You would need to figure out the script though.

**Comment by martincaddick** [comment]
gotcha. Burning the image with the raspberry pi imager allows configuration. Just thought that may be suitable.
<img width="518" alt="image" src="https://user-images.githubusercontent.com/73564857/184134205-16f653b6-3f39-4140-b1a6-79b9686c774a.png">

**Comment by mgrouch** [comment]
I haven't tested that scenario. It's good idea to make it work too. I haven't tried it though so I can't say it's supported at the moment. Might be for future Bullseye based releases.

**Comment by RichFind** [comment]
> I haven't tested that scenario. It's good idea to make it work too. I haven't tried it though so I can't say it's supported at the moment. Might be for future Bullseye based releases.

I tried using it, didn't work.

**Comment by mgrouch** [comment]
Definitely no plans to support it as it changes user too. 
The BBN documentation now mentions that image needs to be burned as-is without using advanced rpi imager features.

**Comment by mgrouch** [comment]
Added proper SD card burning procedure to the documentation. 
I do not see it feasible to test all rpi imager advanced options combinations which modify already tested image.
