### ISSUE TITLE
Support for other boards

### ISSUE THREAD

**Issue by mgrouch** [bareboat-necessities/lysmarine_gen#255]
Support for other ARM boards. (Based on Armbian Bullseye)

- Orange Pi 5 4/8GB
- Orange Pi 800 4GB
- Banana Pi BPI-M2S 4GB
- Banana Pi BPI-M5 4GB
- Libre Computer Renegade 4GB
- Libre Computer Renegade Elite 4GB
- Rock Pi 4 C+ 4GB
- OKdo x Radxa ROCK 4 Model SE 4GB Single Board Computer Rockchip RK3399-T ARM Cortex-A72
- DEBIX Model A: Industrial Single Board Computer 4-6GB
- Khadas VIM4 8GB
- Khadas VIM3 Pro 4GB
- FireFly ROC Series ROC-RK3588-PC
- FireFly ROC Series ROC-RK3399-PC
- Odroid C4
- Pinebook Pro Laptop (4GB) RK3399
- QUARTZ64 Model-A 8GB RK3566
- Station M2 8GB RK3566

**Comment by mgrouch** [comment]
RK3399 based ones seems best contenders so far:

Rock Pi 4 C+ 4GB
Orange Pi 4 LTS 4GB

(No 8GB versions though)

**Comment by mgrouch** [comment]
Banana Pi are also interesting. Banana Pi has also scaled down (in features) CM4

**Comment by mgrouch** [comment]
Inovato Quadra is quite interesting (2GB) 

https://www.inovato.com/

It's Armbian for TV Boxes:

https://www.inovato.com/article/install
https://forum.armbian.com/topic/24085-csc-armbian-for-rk3318rk3328-tv-box-boards/

**Comment by mgrouch** [comment]
Odroid M1 seems to be the best choice at
this point

**Comment by peronosporos** [comment]
Maybe an alternative could be to make a proxmox script for emulation on x86 computers. There are some cheap server computers on the market that could be used instead of the ARM ones.

**Comment by mgrouch** [comment]
Risc-V boards 

Waveshare VisionFive2 RISC-V Single Board Computer, StarFive JH7110 Processor with Integrated 3D GPU, 4GB Memory, Without WiFi Module

https://hackaday.com/2023/03/06/the-future-of-risc-v-and-the-visionfive-2-single-board-computer/

**Comment by pandaero** [comment]
I have a RockPi 4C+ 4GB, I can finally connect it to the boat and an HDMI monitor, and my network + internet. 

I am seeing how to build an image for it, and made a fork, circleCI, and cloudsmith account. Since it is not a raspberry pi, I think I can't make a raspbian-based image, so I'm considering Armbian, but I have no idea what to change in the different scripts and config to generate an armbian arm64 image for the board. [This](https://github.com/pandaero/BBN-OS-RockPi) is the fork, so far there are no changes.

I would need help to get started but can test the images on my hardware.

**Comment by mgrouch** [comment]
You will need to edit the scripts 
to use base image as Armbian for your board 
(Bullseye arm64 based)

and start working from there. 

Debian packages would be compatible. 

only some raspberry specific configurations would be different. As well as some raspberry specific packages. 

I would comment out some things for a start 
and focus on building an images that boots. 

Then on small image that boots into UI. 

Then then I would start adding things back.

**Comment by mgrouch** [comment]
Here is link to images
https://mirrors.aliyun.com/armbian-releases/rockpi-4cplus/archive/

**Comment by mgrouch** [comment]
If you give me commit permissions to your github repo and CircleCi to see logs
I can help you getting started

**Comment by pandaero** [comment]
> If you give me commit permissions to your github repo and CircleCi to see logs I can help you getting started

I just invited you as a collaborator, thank you so much! How can I send you the CircleCI permissions?

**Comment by mgrouch** [comment]
Update:

I had to drop pypilot, pi related plugins from SignalK and RealVNC server (I think it can be replaced with another VNC server but it will not have cloud access support as RealVNC (that's paid service))

I'll see what else I'll encounter. GPIO probably will have permissions issue. (armbian by default allows only root user access to it)

I had to remove rpi-imager and rpi-clone too

Code is here:

https://github.com/pandaero/BBN-OS-RockPi/tree/armbian-bullseye-dev

**Comment by mgrouch** [comment]
@pandaero 
@peronosporos 

The first image is built. No idea if it boots fine. Can you try?

https://cloudsmith.io/~heavenly-tech/repos/bbn-os-rockpi/packages/?q=lysmarine

**Comment by pandaero** [comment]
@mgrouch 
I prepared a microSD with Etcher and according to the status LEDs (green with flashing blue, RockPi 4C+ v 1.41), the system has booted! However there is no HDMI output, and I have no way of connecting to the board with ethernet (for now).

**Comment by mgrouch** [comment]
@pandaero 
@peronosporos 

Did it create WiFi hotspot?
lysmarine-hotspot with password 
changeme?

If it did you can try connecting via wifi and ssh.

**Comment by mgrouch** [comment]
Try pressing Ctrl-Alt-F1. 
does console show?

**Comment by mgrouch** [comment]
I’ve put different base image now into build. 
when it completes you can try it too

**Comment by pandaero** [comment]
The new image also seems to boot according to the status LED, but it does not have HDMI output and does not broadcast a lysmarine-hotspot network (also not a hidden network)

**Comment by pandaero** [comment]
I found this source of images for the 4C+ from Armbian: https://mirrors.dotsrc.org/armbian-dl/rockpi-4cplus/archive/

**Comment by mgrouch** [comment]
You can try burning desktop version of it into separate SD card and see what configs are on it /boot/armbianEnv.txt etc

Then try to compare with what is on BBN Armbian version.

I’ll leave to you to troubleshoot further as I have no rockpi hardware. 

The build of image works (the image itself doesn’t :))

**Comment by pandaero** [comment]
I managed to boot, only with the image v22.0.5 - jammy - 6.1.33 - cinnamon desktop (xfce didn't boot).

in /boot/armbianEnv.txt there is:
```
verbosity=1
bootlogo=true
overlay_prefix=rockchip
fdtfile=rockchip/rk3399-rock-pi-4c-plus.dtb
rootdev=UUID=(doesn't matter)
rootfstype=ext4
usbstoragequirks=0x2537:0x1066:u,0x2537:0x1068:u`
```
I don't know what "etc." would be or how to compare it to the BBN Armbian version

**Comment by mgrouch** [comment]
Are you saying all bullseye desktop versions provided by Armbian for your board do not work for you?

**Comment by pandaero** [comment]
> Are you saying all bullseye desktop versions provided by Armbian for your board do not work for you?

I'll check, I didn't see any desktop versions

**Comment by pandaero** [comment]
Ok I managed to boot with image: Armbian v22.05.2 - bullseye (current) - 6.1.33

**Comment by pandaero** [comment]
> Ok I managed to boot with image: Armbian v22.05.2 - bullseye (current) - 6.1.33

The file /boot/armbianEnv.txt is the same except `bootlogo=false`

**Comment by mgrouch** [comment]
You can copy .xz BBN image file somewhere unpack it and mount as file system. 

And start checking what are your he differences in configs that hdmi works on one but not on another.

**Comment by mgrouch** [comment]
Or if you have usb with sd card adapters you can use two sd cards one with BBN you are testing and another working one

**Comment by pandaero** [comment]
Gosh I'm sorry, apparently the 4K microHDMI port works while the 2K microHDMI port does not! Good news that it's now working (later image)

I get a prompt with user@lysmarine:~$, then a desktop environment with BBN OS apparently working!

**Comment by mgrouch** [comment]
Fixed few important issues in latest

2023-07-29

https://cloudsmith.io/~heavenly-tech/repos/bbn-os-rockpi/packages/?q=lysmarine

**Comment by mgrouch** [comment]
Seems no one is asking for it anymore now that Pi are available in stores

**Comment by velvetant** [comment]
> Maybe an alternative could be to make a proxmox script for emulation on x86 computers. There are some cheap server computers on the market that could be used instead of the ARM ones.

I am all for this and would be willing to help where I can.

**Comment by mgrouch** [comment]
It's not difficult to make a Debian Intel image. I've made i2c via USB device. So you can connect i2c sensors with it to Debian
running on Intel PC without having i2c hardware. The required drivers are already in Debian Linux kernel.

https://github.com/bareboat-necessities/bbn-i2c-over-usb
