### ISSUE TITLE
Boat app locked up

### ISSUE THREAD

**Issue by Tosca36** [bareboat-necessities/lysmarine_gen#313]
I entered all the boat information again as it didn't save it and tried to go back in and I can't open it, I can open other apps like signalk, radio and others, I restarted the pi and still not able to open the boat app? Any help would be much appreciated!

**Comment by mgrouch** [comment]
Do

rm -r /home/user/.vessel 

and start app. 
enter your data without using special characters 

like quotes etc

**Comment by Tosca36** [comment]
Hello Mikhail! I ran that command just like you have it written and went back into vessel app and still couldn’t open it. Any suggestions? Thank you john

**Comment by Tosca36** [comment]
Sorry! Also opencpn is running very slow, is there a way to speed it up? I can’t find the settings for OpenGL

**Comment by Tosca36** [comment]
Hello Mikhail! What should I choose to make opencpn faster,also did grip command in the terminal and open cpn shows an error?  also it doesn’t seem to scale the charts when you pan closer? Thank you Mikhail!!! JohnThank you john

**Comment by mgrouch** [comment]
You need to have BBN OS

version 2023-06-15  (or 13)

for OpenCPN to run fast.

**Comment by Tosca36** [comment]
Do I need to start over with the new version or can I update what I have now?

**Comment by mgrouch** [comment]
You need to install new image and apply same changes you done before. Hopefully you scripted them somewhere or just made notes how to reproduce them.
