### ISSUE TITLE
i lost my own position and own vessel colored by grey 

### ISSUE THREAD

**Issue by Topaz12244** [bareboat-necessities/lysmarine_gen#317]
hi, we just lost all ais, own vessel position and now became grey and position cannot detect.

we have checked all connections are good from AIS port to PC any suggestions.?

**Comment by mgrouch** [comment]
Try restarting SignalK. 
click command icon on desktop and there is option to restart SignalK from touchscreen

**Comment by mgrouch** [comment]
If that doesn’t help. Reboot pi

**Comment by Topaz12244** [comment]
> 

i opened command but there is no option to restart singalK

**Comment by mgrouch** [comment]
Click an icon on desktop tilted ‘Commands’
Third row. Middle

**Comment by Topaz12244** [comment]
> Click an icon on desktop tilted ‘Commands’ Third row. Middle

hi dear, i can't find any icon on my pc desktop named by command.

**Comment by mgrouch** [comment]
![IMG_5105](https://github.com/bareboat-necessities/lysmarine_gen/assets/8263013/5728424d-9f6e-4517-94de-66b491b96872)

**Comment by mgrouch** [comment]
Third row middle

**Comment by Topaz12244** [comment]
> ![IMG_5105](https://user-images.githubusercontent.com/8263013/248916683-5728424d-9f6e-4517-94de-66b491b96872.png)

thank you for trying help me .

moreover i`m installed opencpn on computer PC in my boat and connected AIS to CPU of the computer by Cable.

**Comment by mgrouch** [comment]
So you are not using BBN OS then. 
it’s AIS to PC via cable. What kind of cable?
