### ISSUE TITLE
Scaling?

### ISSUE THREAD

**Issue by bailout00** [bareboat-necessities/lysmarine_gen#326]
Is there any way to change the UI scaling manually? Everything is TINY, "scale down" app helps slightly but the main UI still only takes up about 1/4 of the screen and the buttons are too small for a touch screen.

**Comment by mgrouch** [comment]
Go into budgie desktop settings and increase font scale from 1 to higher value

**Comment by bailout00** [comment]
Yea, just found that in the docs, I have all of those settings up but now everything is just wonky. The gnome scaling settings are missing... going to try gnome-tweaks

**Comment by mgrouch** [comment]
Attach a screenshot
