### ISSUE TITLE
Cloudsmith Download links HTTP402

### ISSUE THREAD

**Issue by CaptainCrackers** [bareboat-necessities/lysmarine_gen#332]
https://dl.cloudsmith.io/public/bbn-projects/bbn-repo/raw/files/lysmarine-bbn-bullseye_2023-07-23-raspios-arm64.img.xz  -> download link for latest returns HTTP402 

Unable to download image. 
![image](https://github.com/bareboat-necessities/lysmarine_gen/assets/68983125/c5b1d54c-dd90-4ea3-a222-ba5a1b223a8e)
![image](https://github.com/bareboat-necessities/lysmarine_gen/assets/68983125/1432c0d1-0d96-4056-a63c-5a0c4d751084)

**Comment by mgrouch** [comment]
You can download from github releases following these instructions 

https://github.com/bareboat-necessities/lysmarine_gen/releases/tag/v2023-07-23
