### ISSUE TITLE
Install - Pi 4 8GB - 10.1 inch Screen

### ISSUE THREAD

**Issue by wsturner88** [bareboat-necessities/lysmarine_gen#353]
Having installed BBN about 10 times now, I thought I knew what I was doing.   Looking to upgrade my boat and add a 10" touch screen.   

On first boot, it resizes the partition.. I get the LYSMARINE splash screen..  Then I get a repeating authentication error.
Tried a few builds 64bit all had the same issue. 

Any recommendations?

**Comment by mgrouch** [comment]
How are you burning your SD card? Are you changing name or password in Raspberry pi imager? You shouldn’t do that if you are doing it. Burn image as-is.

**Comment by wsturner88** [comment]
Good Thought, I have been using a 16GB Samsung USB stick.    For some other applications I found it much faster than the SD card.

YES I did change name and password in imager...      Will try without that as well.

**Comment by mgrouch** [comment]
If you changed user or password by imager you will get the error you are receiving

**Comment by wsturner88** [comment]
THANK YOU!

**Comment by mgrouch** [comment]
![IMG_5953](https://github.com/bareboat-necessities/lysmarine_gen/assets/8263013/7d12654a-a9c8-46a6-86f4-7eabfbcf3e67)

**Comment by wsturner88** [comment]
SOLVED
