### ISSUE TITLE
Support for Raspberry Pi 5?

### ISSUE THREAD

**Issue by tingles2233** [bareboat-necessities/lysmarine_gen#360]
As the title says support for Raspberry Pi 5? 

Most likely means a port over to Bookworm from Bullseye.

**Comment by mgrouch** [comment]
Let’s see how many people actually need it. 
Please comment 
+1 if you need pi5 version

**Comment by Starcrest2020** [comment]
÷1

**Comment by tingles2233** [comment]
The big win for me with this is the faster processor which allows for in our case as it is positioned as a multipurpose device we can watch proper full resolution 4K web streams. All other functions would also benefit from the overall speed increase.

**Comment by mgrouch** [comment]
> The big win for me with this is the faster processor which allows for in our case as it is positioned as a multipurpose device we can watch proper full resolution 4K web streams. All other functions would also benefit from the overall speed increase.

Speed increase in pi5 comes with higher power consumption as a con.

**Comment by tingles2233** [comment]
Not wrong rpi5 idle power consumption is around 3.4watts compared to the idle of the rpi4 at 2.8watts in my testing. 

Other then actively watching a video the pi seems to stay at idle power consumption. Even with opencpn running it doesn’t seem to consume more(on the rpi4) that is I would assume the rpi5 would be the same in that regard.

**Comment by mgrouch** [comment]
You can monitor the progress on test images which are appearing here

https://cloudsmith.io/~bbn-projects/repos/bbn-repo/packages/?q=bookworm

**Comment by mgrouch** [comment]
BBN Lite version based on bookworm looks pretty good already. Here are known issues 

- application Menu organization changed
- pypilot motor controller (untested on pi5, it seems to be working on pi4)
- OpenCPN dashboard plugins behave weird. They open too big windows (fixed by adjusting openbox rc.xml)
- Slow start of web browser (--password-store=basic argument to chromium-browser seems fixes it)
- Gtk3 theme window toolbar icons are too close to each other for touchscreen 

Seems

On bookworm version for pypilot motor controller UART you also need to disable the hciuart service, which initialises the Bluetooth modem:
````
sudo systemctl disable hciuart
````

Report here if you see other issues with BBN Lite

BBN Full version on bookworm is still missing features:

- Pypilot calibration tool issues with compass calibration screen 
- Missing facebook messenger (caprine)
- Mopidy no audio 
- WinLink PAT is missing

**Comment by tingles2233** [comment]
Thanks, I’ll be doing testing first week in Jan and report back with my findings.

**Comment by mgrouch** [comment]
BBN Lite version based on bookworm looks pretty good already. Here are known issues

- application Menu organization changed
- pypilot motor controller (untested on pi5, it seems to be working on pi4)
- no password popup on connecting to new Wi-Fi

On bookworm version for pypilot motor controller UART you also need to disable the hciuart service, which initialises the Bluetooth modem:

````
sudo systemctl disable hciuart
````

Report here if you see other issues with BBN Lite

BBN Full version on bookworm no longer is missing features but has known issues:

- Pypilot calibration tool issues with compass calibration screen
- Mopidy no audio
- no password popup on connecting to new Wi-Fi
- Web cam app doesn't start (seg faults)

**Comment by mgrouch** [comment]
This https://github.com/mopidy/mopidy/issues/1974
seems related to mopidy audio issues

**Comment by mgrouch** [comment]
Remaining (known) issues

Pypilot calibration tool issues with compass calibration screen (in FULL version)
https://github.com/pypilot/pypilot/issues/216


No password popup on connecting to new Wi-Fi
https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/1461
(as workaround you can enter password later in WiFi settings)
https://github.com/BuddiesOfBudgie/budgie-desktop/issues/508

Is this bacause of nm-applet --indicator    ?


Web cam app doesn't start (seg faults) (affects FULL version)
https://gitlab.gnome.org/GNOME/cheese/-/issues/174


Application menu organization changed
https://github.com/BuddiesOfBudgie/budgie-desktop/issues/507
https://github.com/BuddiesOfBudgie/budgie-desktop/issues/506

**Comment by mgrouch** [comment]
No password popup on connecting to new Wi-Fi was fixed with using lightdm since BBN OS version 2024-01-28

**Comment by mgrouch** [comment]
Remaining (known) issues

Pypilot calibration tool issues with compass calibration screen (in FULL version)
https://github.com/pypilot/pypilot/issues/216
Calibration (compass and acceperometer) in FULL version is missing spheres in UI.
No calibration data is displayed in left bottom text area.


Web cam app doesn't start (seg faults) (affects FULL version)
https://gitlab.gnome.org/GNOME/cheese/-/issues/174

Application menu organization changed
https://github.com/BuddiesOfBudgie/budgie-desktop/issues/507
https://github.com/BuddiesOfBudgie/budgie-desktop/issues/506

**Comment by 5lav0** [comment]
+1

**Comment by mgrouch** [comment]
webcam and app menu organization issues and fixed

**Comment by mgrouch** [comment]
Remaining (known) issues

Pypilot calibration tool issues with compass calibration screen
https://github.com/pypilot/pypilot/issues/216

**Comment by mgrouch** [comment]
UPDATE:

As of 2024-02-08 version I do not see any issues in LITE version.
FULL version has only one issue known to me and it is pypilot_calibration for compass and accelerometer (seems to be 
libraries versions mismatch between LITE and FULL BBN OS versions)

The issues reported so far turned out to be hardware issues with users hardware and not with BBN OS software

**Comment by mgrouch** [comment]
Remaining (known) issues

Pypilot calibration tool issues with compass calibration screen in FULL version 
https://github.com/pypilot/pypilot/issues/216
Calibration (compass and accelerometer) in FULL version is missing spheres in UI.
No calibration data is displayed in left bottom text area.

pigpiod and any pigpio specific features wouldn’t work
on pi5. Seatalk1 SignalK plugin which requires pigpiod and pypilot hat UI will no longer be supported.
Details: https://forums.raspberrypi.com/viewtopic.php?t=359742

Pypilot motor controller and IMU are supported.

**Comment by mgrouch** [comment]
The first release with bookworm and support for raspberry pi 5 is out.
Closing

**Comment by mgrouch** [comment]
pi5 is supported by both LITE and FULL version since Release:

https://github.com/bareboat-necessities/lysmarine_gen/releases/tag/v2024-02-12.1
