### ISSUE TITLE
GPS Connection error - New user, may be my issue

### ISSUE THREAD

**Issue by Techstyleuk** [bareboat-necessities/lysmarine_gen#363]
GPS shows ups as ttyLYS_gps_0 and getting no GPS feed in Signal K.

ls -l /dev/ttyLYS*
lrwxrwxrwx 1 root root 7 Dec 23 19:29 /dev/ttyLYS_gps_0 -> ttyUSB0
lrwxrwxrwx 1 root root 7 Dec 23 19:29 /dev/ttyLYS_prolific_ -> ttyUSB0

updated the GPS1 entry in Signal K from '/dev/ttyLYS_gps_1' to '/dev/ttyLYS_gps_0', then GPS signal successfully received by Signal K.

I am new to BBN so maybe there is a way to handle this similar to Openplotter Serial, so let me know if I am just doing this wrong

version is 'test-bbn-bookworm_2023-12-21-r2010-raspios-arm64' on RPi5

**Comment by mgrouch** [comment]
Just edit /etc/default/gpsd.conf 

and add 
/dev/ttyLYS_gps_0

to devices

**Comment by mgrouch** [comment]
````
DEVICES="/dev/ttyLYS_gps_0"
````

in  /etc/default/gpsd

and 

````
sudo systemctl restart gpsd
````
