### ISSUE TITLE
Bookworm drivers

### ISSUE THREAD

**Issue by pancirm** [bareboat-necessities/lysmarine_gen#371]
Bookworm
It does not recognize the rtL8188EU, nor the LTE 4G modem. Touch Screen does not work.

**Comment by mgrouch** [comment]
Check with vendors of rtL8188EU, and your LTE 4G modem regarding support on Raspberry pi5 Bookworm.

Need more information about your touchscreen here

**Comment by pancirm** [comment]
Thanks for the response.
I'm using RPI 4. In that case Bullseye(lysmarine-bbn-bullseye_2023-08-17-raspios-arm64) will probably be better than Bookworm.?.? 
In Bullseye, I have a problem with updating SignalK to version 2.5...

**Comment by mgrouch** [comment]
SignalK 2.5 is in bookworm version. Update to SignalK 2.5 will not be supported by BBN bullseye.
Bookworm version is still beta but 2024-02-08 already works pretty good both on pi4 and pi5.

**Comment by mgrouch** [comment]
Did you pick the touchscreen which is supported in Raspberry pi OS?

**Comment by pancirm** [comment]
https://www.waveshare.com/13.3inch-hdmi-lcd-h-with-case.htm
And this is the modem that works in Bullseye https://www.aliexpress.com/item/1005004134750959.html

**Comment by mgrouch** [comment]
What is the output of 

`lsusb`

`ls -l /dev/touch*`

and

`cat /usr/share/X11/xorg.conf.d/90-touchinput.conf`

Thanks

**Comment by pancirm** [comment]
user@lysmarine:~ $ lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 1546:01a7 U-Blox AG [u-blox 7]
Bus 001 Device 004: ID 214b:7250 Huasheng Electronics USB2.0 HUB
Bus 001 Device 003: ID 1a86:7523 QinHeng Electronics CH340 serial converter
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

user@lysmarine:~ $ ls -l /dev/touch*
ls: cannot access '/dev/touch*': The directory or file does not exist

user@lysmarine:~ $ cat /usr/share/X11/xorg.conf.d/90-touchinput.conf
cat: /usr/share/X11/xorg.conf.d/90-touchinput.conf: The directory or file does not exist

**Comment by mgrouch** [comment]
I do not see that your touchscreen is plugged in onto USB.
Are you sure you made the connection?

**Comment by mgrouch** [comment]
In 'System Profiler and Benchmarks' UI Tool under section Devices/Input Devices do you see your touchscreen input device?

**Comment by pancirm** [comment]
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 1546:01a7 U-Blox AG [u-blox 7]
Bus 001 Device 008: ID 222a:0001 ILI Technology Corp. Multi-Touch Screen
Bus 001 Device 004: ID 214b:7250 Huasheng Electronics USB2.0 HUB
Bus 001 Device 009: ID 1a86:7523 QinHeng Electronics CH340 serial converter
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

I can already see where the problem is. If I connect the Touchscreen via the HUB, it does not work, and this will probably be a problem with other devices as well...
HUB https://www.aliexpress.com/item/1005004682611725.html

**Comment by mgrouch** [comment]
Some USB hubs are poorly designed and will have all sorts of issues with Raspberry.

**Comment by pancirm** [comment]
Anyway, thanks a lot for your help...
One more little thing. It also happened to me after apt update and upgrade that the contents of the directory /usr/share/opencpn/ changed and Opencpn could not be started.

**Comment by mgrouch** [comment]
I'll add 

`apt-mark hold opencpn` 

for next version

so people will stop upgrading it blindly and breaking things

Thanks

**Comment by pancirm** [comment]
Ok Thanks. Otherwise it's super well done. High praise.

**Comment by mgrouch** [comment]
Thanks. I'm closing this one. Looks like hardware issue with the USB hub.
Please report any other issues so they can be fixed before the release.

**Comment by Lucan07** [comment]
May be the BUG in debian distro thats passed down through many other distros, get latest from debian.org, it stopped creating /dev/serial at some point. fixed in bookworm latest

**Comment by mgrouch** [comment]
There is bookworm based BBN release already. 
is this bug report still relevant?

**Comment by mgrouch** [comment]
I think it was fixed in BBN bullseye too. 
is this udev Debian bug?

**Comment by Lucan07** [comment]
I believe so, think it popped up in 5/12/23 release sorted again in 11/12.23 release
