### ISSUE TITLE
influxDB error 404 with fresh 	lysmarine-bbn-bullseye_2023-08-17 install

### ISSUE THREAD

**Issue by gildas-declercq** [bareboat-necessities/lysmarine_gen#381]
Hi,

I had see issue. 
as it was with an install on wich I did some updates , I did a fresh install. 
signalk is ok,
I just have a usb mouse GPS, data are ok
and a can hat , and I have the data ok from nmea2K.
I did 
sudo systemctl unmask influxdb.service
sudo systemctl enable influxdb
sudo systemctl start influxdb

as per documentation.
but cant get anything on http://localhost:8086/  except a 404 error.

what did I do wrong ?
thanks a lot
Gildas

**Comment by mgrouch** [comment]
Yes, that’s right, on port 8086 you will see a 404 page. The browser will complain: “This site could not be reached” if the database is not found.

**Comment by mgrouch** [comment]
and that port is without UI. it's API port.
UI for influxDb is Chronograf.


https://docs.influxdata.com/chronograf/v1/

**Comment by mgrouch** [comment]
````
sudo systemctl enable chronograf
sudo systemctl start chronograf
````

And open browser http://localhost:8888/

Start kapacitor

````
sudo systemctl enable kapacitor
sudo systemctl start kapacitor
````

Create connection to it in Chronograf.

**Comment by gildas-declercq** [comment]
ok got it
thanks a lot
by the way there is a mistype in https://bareboat-necessities.github.io/my-bareboat/bareboat-os.html#_influxdb
"kapasitor" instead of "kapacitor"

regards
