### ISSUE TITLE
download link is broken

### ISSUE THREAD

**Issue by SERGImolina90** [bareboat-necessities/lysmarine_gen#450]
hi, sorry to bother, i try to download the image file and no matter what file i try to download, it doesn't work. I've already contacted the Cloudsmith support and seems that it's broken from the owner's side. Could you please check?
thanks for the support

**Comment by mgrouch** [comment]
It’s not broken. It’s out of quotas on cloudsmith for this month. Use alternative method from release notes.  

https://github.com/bareboat-necessities/lysmarine_gen/releases
