### ISSUE TITLE
404 in Open CPN when 

### ISSUE THREAD

**Issue by cornelledepag** [bareboat-necessities/lysmarine_gen#81]
When trying to download the pypilot plugin I get the following error:

The requested URL returned error: 404 ...

I tried installing and updating other plugins and this was done without a problem. Maybe this is a temporary issue due to plugin repository containing wrong URLs.

**Comment by mgrouch** [comment]
Which plugin gives you 404? 
thanks

**Comment by cornelledepag** [comment]
Pypilot including beta versions

**Comment by mgrouch** [comment]
Sounds like OpenCPN bug. You should report it here https://github.com/OpenCPN/OpenCPN/issues
Thanks

**Comment by mgrouch** [comment]
https://github.com/OpenCPN/OpenCPN/issues/2315
